version: 0.2

eb_codebuild_settings:
  artifacts:
    files:
      - "**/*"
  commands:
    - echo "Preparing the build for Elastic Beanstalk..."

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - python -m unittest discover tests

  build:
    commands:
      - echo "Building application..."

  post_build:
    commands:
      - echo "Post build actions..."

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "pip"
